{% set version = "1.2" %}
{% set sha256 = "66f0d3870b442e715de23b632e83f27f5971885b40bb3f6b211437138c554496" %}

package:
  name: prefsync
  version: {{ version }}

source:
  fn: prefsync-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/prefsync/prefsync-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1002
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - prefsync

  commands:
    - python -m prefsync --help
    - prefsync --help

about:
  home: https://github.com/asmeurer/prefsync
  license_file: LICENSE
  license: MIT
  summary: |
    A little tool to help synchronize Mac OS X plist files (used for
    preferences for most Mac Apps) seamlessly, in a way that can be tracked by
    git.
  doc_url: https://github.com/asmeurer/prefsync
  dev_url: https://github.com/asmeurer/prefsync

extra:
  recipe-maintainers:
    - asmeurer
