appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PQM9Hhuq/XQAdVm0yzIQ/PO+E+DaXtQDWOqbifATwiZC9C0Mxl+hMZiSnbOT/HWxZJj6tV2rrnfvvFI9si+OFw3TmLRZ1a/CCpQO762f+h7h8CZunv1mPeKaVwaSZyUVJ3gwKhXlbj/zP+Gb/zQJeMqTnLF4NCEA1VxCufvCw4tUoe2JgVm56xsf6sq7C6cR7S4fq+jBd1UQPuXdAxDsBhLIVLeX6cTQDKhzIcU+zEtmWno8lscko2ldKTwyFSHgUwSOE7GPhFqak0gNGmchG0mgqLakzUa7vlcWDpxWTtQKPZGbV74S7+Fz8uMh480K61h3xCH7ZdvgPld9d2tCo/ph5/kPczqCpJVLXXEdzczF3EqNJBi3H/czICLMsae1D5jouxTqHCaTE0JN5Wh8SlIA2infUztRt7m2apkKzuhVdoYfPh07Djj/kGxoaqE1a6Zh9D7Pc4sXvFezsKvv7ZmCQG59kLeHbgBoUY0N2apEKiOxkQ2R27CICcmZPUDWx/Mq/Qv1ry1ykaPOy3Ox0vO3JWMBkjj4xwXF5IGk8z6gi25+sO4Ndb92oo+N7vAf/I2mIQSYiaFiQkaQiLccXV0bsBDZDWxzbEm0JB0O6fmD96iPWtX0MT+nf49c98dcHNhR5BKLMOb6HLGouRUFc6xy9dso7o0bqn/NjvpvaQ8=}
